# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxii2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='auth',
            field=models.CharField(default=b'Not sure what to put here', max_length=128),
        ),
        migrations.AddField(
            model_name='channel',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='conn_limits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='contact',
            field=models.CharField(default='mdavidson@soltra.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.CharField(default='This is a demonstration channel', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='idle_timeout',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='max_post_msg_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='msg_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='queue_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.CharField(default=b'Field not implemented yet', max_length=128),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
