# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxii2', '0002_auto_20160225_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='max_get_msg_size',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='auth',
            field=models.CharField(default=b'???', max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='conn_limits',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='contact',
            field=models.CharField(default=b'mdavidson@soltra.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='channel',
            name='idle_timeout',
            field=models.IntegerField(default=3600, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='max_post_msg_size',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='msg_age',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='queue_size',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
