# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxii2', '0003_auto_20160225_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='Some description', max_length=128),
            preserve_default=False,
        ),
    ]
